----------------------------------------
-- Generated by Iris Generator
-- The 7/15/2014 at 1:47 PM
-- The %D% at %T% :Organizations
-- 5 stored procedures to generate.


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Organizations_Select_All'))
drop procedure sp_Organizations_Select_All


GO


Create Procedure sp_Organizations_Select_All
AS
BEGIN
    SELECT [Id],[PublicId],[Name],[Active]
    FROM [dbo].[Organizations]
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Organizations_Select_One'))
drop procedure sp_Organizations_Select_One


GO


Create Procedure sp_Organizations_Select_One
(
@Id int
)
AS
BEGIN
    SELECT [Id],[PublicId],[Name],[Active]
    FROM [dbo].[Organizations]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Organizations_Insert'))
drop procedure sp_Organizations_Insert


GO


Create Procedure sp_Organizations_Insert
(
@PublicId uniqueidentifier,
@Name varchar(150),
@Active bit
)
AS
BEGIN
    INSERT INTO [dbo].[Organizations]
    (
        [PublicId],
[Name],
[Active]
    )
    VALUES
    (
        @PublicId,
@Name,
@Active

    )
    Select @@identity;
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Organizations_Delete'))
drop procedure sp_Organizations_Delete


GO


Create Procedure sp_Organizations_Delete
(
@Id int
)
AS
BEGIN
    DELETE FROM [dbo].[Organizations]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Organizations_Update'))
drop procedure sp_Organizations_Update


GO


Create Procedure sp_Organizations_Update
(
@Id int,
@PublicId uniqueidentifier,
@Name varchar(150),
@Active bit
)
AS
BEGIN
    UPDATE [dbo].[Organizations]
    SET
        [PublicId]=@PublicId,
        [Name]=@Name,
        [Active]=@Active
WHERE        [Id]=@Id
END

GO


-- The %D% at %T% :OrganizationUsers
-- 7 stored procedures to generate.


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Select_OrganizationUserss_By_OrganizationId'))
drop procedure sp_Select_OrganizationUserss_By_OrganizationId


GO


Create Procedure sp_Select_OrganizationUserss_By_OrganizationId
(
@OrganizationId int
)
AS
BEGIN
    SELECT [Id],[OrganizationId],[UserId],[Active]
    FROM [dbo].[OrganizationUsers]
    WHERE
        [OrganizationId]=@OrganizationId
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Select_OrganizationUserss_By_UserId'))
drop procedure sp_Select_OrganizationUserss_By_UserId


GO


Create Procedure sp_Select_OrganizationUserss_By_UserId
(
@UserId int
)
AS
BEGIN
    SELECT [Id],[OrganizationId],[UserId],[Active]
    FROM [dbo].[OrganizationUsers]
    WHERE
        [UserId]=@UserId
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_OrganizationUsers_Select_All'))
drop procedure sp_OrganizationUsers_Select_All


GO


Create Procedure sp_OrganizationUsers_Select_All
AS
BEGIN
    SELECT [Id],[OrganizationId],[UserId],[Active]
    FROM [dbo].[OrganizationUsers]
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_OrganizationUsers_Select_One'))
drop procedure sp_OrganizationUsers_Select_One


GO


Create Procedure sp_OrganizationUsers_Select_One
(
@Id int
)
AS
BEGIN
    SELECT [Id],[OrganizationId],[UserId],[Active]
    FROM [dbo].[OrganizationUsers]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_OrganizationUsers_Insert'))
drop procedure sp_OrganizationUsers_Insert


GO


Create Procedure sp_OrganizationUsers_Insert
(
@OrganizationId int,
@UserId int,
@Active bit
)
AS
BEGIN
    INSERT INTO [dbo].[OrganizationUsers]
    (
        [OrganizationId],
[UserId],
[Active]
    )
    VALUES
    (
        @OrganizationId,
@UserId,
@Active

    )
    Select @@identity;
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_OrganizationUsers_Delete'))
drop procedure sp_OrganizationUsers_Delete


GO


Create Procedure sp_OrganizationUsers_Delete
(
@Id int
)
AS
BEGIN
    DELETE FROM [dbo].[OrganizationUsers]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_OrganizationUsers_Update'))
drop procedure sp_OrganizationUsers_Update


GO


Create Procedure sp_OrganizationUsers_Update
(
@Id int,
@OrganizationId int,
@UserId int,
@Active bit
)
AS
BEGIN
    UPDATE [dbo].[OrganizationUsers]
    SET
        [OrganizationId]=@OrganizationId,
        [UserId]=@UserId,
        [Active]=@Active
WHERE        [Id]=@Id
END

GO


-- The %D% at %T% :Reports
-- 6 stored procedures to generate.


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Select_Reportss_By_OrganizationId'))
drop procedure sp_Select_Reportss_By_OrganizationId


GO


Create Procedure sp_Select_Reportss_By_OrganizationId
(
@OrganizationId int
)
AS
BEGIN
    SELECT [Id],[OrganizationId],[PublicId],[Name],[Controller],[Action]
    FROM [dbo].[Reports]
    WHERE
        [OrganizationId]=@OrganizationId
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Reports_Select_All'))
drop procedure sp_Reports_Select_All


GO


Create Procedure sp_Reports_Select_All
AS
BEGIN
    SELECT [Id],[OrganizationId],[PublicId],[Name],[Controller],[Action]
    FROM [dbo].[Reports]
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Reports_Select_One'))
drop procedure sp_Reports_Select_One


GO


Create Procedure sp_Reports_Select_One
(
@Id int
)
AS
BEGIN
    SELECT [Id],[OrganizationId],[PublicId],[Name],[Controller],[Action]
    FROM [dbo].[Reports]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Reports_Insert'))
drop procedure sp_Reports_Insert


GO


Create Procedure sp_Reports_Insert
(
@OrganizationId int,
@PublicId uniqueidentifier,
@Name varchar(50),
@Controller varchar(50),
@Action varchar(50)
)
AS
BEGIN
    INSERT INTO [dbo].[Reports]
    (
        [OrganizationId],
[PublicId],
[Name],
[Controller],
[Action]
    )
    VALUES
    (
        @OrganizationId,
@PublicId,
@Name,
@Controller,
@Action

    )
    Select @@identity;
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Reports_Delete'))
drop procedure sp_Reports_Delete


GO


Create Procedure sp_Reports_Delete
(
@Id int
)
AS
BEGIN
    DELETE FROM [dbo].[Reports]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Reports_Update'))
drop procedure sp_Reports_Update


GO


Create Procedure sp_Reports_Update
(
@Id int,
@OrganizationId int,
@PublicId uniqueidentifier,
@Name varchar(50),
@Controller varchar(50),
@Action varchar(50)
)
AS
BEGIN
    UPDATE [dbo].[Reports]
    SET
        [OrganizationId]=@OrganizationId,
        [PublicId]=@PublicId,
        [Name]=@Name,
        [Controller]=@Controller,
        [Action]=@Action
WHERE        [Id]=@Id
END

GO


-- The %D% at %T% :Roles
-- 5 stored procedures to generate.


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Roles_Select_All'))
drop procedure sp_Roles_Select_All


GO


Create Procedure sp_Roles_Select_All
AS
BEGIN
    SELECT [Id],[PublicId],[Name],[Active]
    FROM [dbo].[Roles]
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Roles_Select_One'))
drop procedure sp_Roles_Select_One


GO


Create Procedure sp_Roles_Select_One
(
@Id int
)
AS
BEGIN
    SELECT [Id],[PublicId],[Name],[Active]
    FROM [dbo].[Roles]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Roles_Insert'))
drop procedure sp_Roles_Insert


GO


Create Procedure sp_Roles_Insert
(
@PublicId uniqueidentifier,
@Name varchar(50),
@Active bit
)
AS
BEGIN
    INSERT INTO [dbo].[Roles]
    (
        [PublicId],
[Name],
[Active]
    )
    VALUES
    (
        @PublicId,
@Name,
@Active

    )
    Select @@identity;
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Roles_Delete'))
drop procedure sp_Roles_Delete


GO


Create Procedure sp_Roles_Delete
(
@Id int
)
AS
BEGIN
    DELETE FROM [dbo].[Roles]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Roles_Update'))
drop procedure sp_Roles_Update


GO


Create Procedure sp_Roles_Update
(
@Id int,
@PublicId uniqueidentifier,
@Name varchar(50),
@Active bit
)
AS
BEGIN
    UPDATE [dbo].[Roles]
    SET
        [PublicId]=@PublicId,
        [Name]=@Name,
        [Active]=@Active
WHERE        [Id]=@Id
END

GO


-- The %D% at %T% :UserReports
-- 7 stored procedures to generate.


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Select_UserReportss_By_ReportId'))
drop procedure sp_Select_UserReportss_By_ReportId


GO


Create Procedure sp_Select_UserReportss_By_ReportId
(
@ReportId int
)
AS
BEGIN
    SELECT [Id],[UserId],[ReportId]
    FROM [dbo].[UserReports]
    WHERE
        [ReportId]=@ReportId
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Select_UserReportss_By_UserId'))
drop procedure sp_Select_UserReportss_By_UserId


GO


Create Procedure sp_Select_UserReportss_By_UserId
(
@UserId int
)
AS
BEGIN
    SELECT [Id],[UserId],[ReportId]
    FROM [dbo].[UserReports]
    WHERE
        [UserId]=@UserId
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_UserReports_Select_All'))
drop procedure sp_UserReports_Select_All


GO


Create Procedure sp_UserReports_Select_All
AS
BEGIN
    SELECT [Id],[UserId],[ReportId]
    FROM [dbo].[UserReports]
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_UserReports_Select_One'))
drop procedure sp_UserReports_Select_One


GO


Create Procedure sp_UserReports_Select_One
(
@Id int
)
AS
BEGIN
    SELECT [Id],[UserId],[ReportId]
    FROM [dbo].[UserReports]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_UserReports_Insert'))
drop procedure sp_UserReports_Insert


GO


Create Procedure sp_UserReports_Insert
(
@UserId int,
@ReportId int
)
AS
BEGIN
    INSERT INTO [dbo].[UserReports]
    (
        [UserId],
[ReportId]
    )
    VALUES
    (
        @UserId,
@ReportId

    )
    Select @@identity;
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_UserReports_Delete'))
drop procedure sp_UserReports_Delete


GO


Create Procedure sp_UserReports_Delete
(
@Id int
)
AS
BEGIN
    DELETE FROM [dbo].[UserReports]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_UserReports_Update'))
drop procedure sp_UserReports_Update


GO


Create Procedure sp_UserReports_Update
(
@Id int,
@UserId int,
@ReportId int
)
AS
BEGIN
    UPDATE [dbo].[UserReports]
    SET
        [UserId]=@UserId,
        [ReportId]=@ReportId
WHERE        [Id]=@Id
END

GO


-- The %D% at %T% :UserRoles
-- 7 stored procedures to generate.


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Select_UserRoless_By_RoleId'))
drop procedure sp_Select_UserRoless_By_RoleId


GO


Create Procedure sp_Select_UserRoless_By_RoleId
(
@RoleId int
)
AS
BEGIN
    SELECT [Id],[RoleId],[UserId],[Active]
    FROM [dbo].[UserRoles]
    WHERE
        [RoleId]=@RoleId
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Select_UserRoless_By_UserId'))
drop procedure sp_Select_UserRoless_By_UserId


GO


Create Procedure sp_Select_UserRoless_By_UserId
(
@UserId int
)
AS
BEGIN
    SELECT [Id],[RoleId],[UserId],[Active]
    FROM [dbo].[UserRoles]
    WHERE
        [UserId]=@UserId
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_UserRoles_Select_All'))
drop procedure sp_UserRoles_Select_All


GO


Create Procedure sp_UserRoles_Select_All
AS
BEGIN
    SELECT [Id],[RoleId],[UserId],[Active]
    FROM [dbo].[UserRoles]
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_UserRoles_Select_One'))
drop procedure sp_UserRoles_Select_One


GO


Create Procedure sp_UserRoles_Select_One
(
@Id int
)
AS
BEGIN
    SELECT [Id],[RoleId],[UserId],[Active]
    FROM [dbo].[UserRoles]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_UserRoles_Insert'))
drop procedure sp_UserRoles_Insert


GO


Create Procedure sp_UserRoles_Insert
(
@RoleId int,
@UserId int,
@Active bit
)
AS
BEGIN
    INSERT INTO [dbo].[UserRoles]
    (
        [RoleId],
[UserId],
[Active]
    )
    VALUES
    (
        @RoleId,
@UserId,
@Active

    )
    Select @@identity;
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_UserRoles_Delete'))
drop procedure sp_UserRoles_Delete


GO


Create Procedure sp_UserRoles_Delete
(
@Id int
)
AS
BEGIN
    DELETE FROM [dbo].[UserRoles]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_UserRoles_Update'))
drop procedure sp_UserRoles_Update


GO


Create Procedure sp_UserRoles_Update
(
@Id int,
@RoleId int,
@UserId int,
@Active bit
)
AS
BEGIN
    UPDATE [dbo].[UserRoles]
    SET
        [RoleId]=@RoleId,
        [UserId]=@UserId,
        [Active]=@Active
WHERE        [Id]=@Id
END

GO


-- The %D% at %T% :Users
-- 5 stored procedures to generate.


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Users_Select_All'))
drop procedure sp_Users_Select_All


GO


Create Procedure sp_Users_Select_All
AS
BEGIN
    SELECT [Id],[PublicId],[UserName],[Email],[Active],[PasswordHash]
    FROM [dbo].[Users]
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Users_Select_One'))
drop procedure sp_Users_Select_One


GO


Create Procedure sp_Users_Select_One
(
@Id int
)
AS
BEGIN
    SELECT [Id],[PublicId],[UserName],[Email],[Active],[PasswordHash]
    FROM [dbo].[Users]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Users_Insert'))
drop procedure sp_Users_Insert


GO


Create Procedure sp_Users_Insert
(
@PublicId uniqueidentifier,
@UserName varchar(50),
@Email varchar(150),
@Active bit,
@PasswordHash varchar(256)
)
AS
BEGIN
    INSERT INTO [dbo].[Users]
    (
        [PublicId],
[UserName],
[Email],
[Active],
[PasswordHash]
    )
    VALUES
    (
        @PublicId,
@UserName,
@Email,
@Active,
@PasswordHash

    )
    Select @@identity;
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Users_Delete'))
drop procedure sp_Users_Delete


GO


Create Procedure sp_Users_Delete
(
@Id int
)
AS
BEGIN
    DELETE FROM [dbo].[Users]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Users_Update'))
drop procedure sp_Users_Update


GO


Create Procedure sp_Users_Update
(
@Id int,
@PublicId uniqueidentifier,
@UserName varchar(50),
@Email varchar(150),
@Active bit,
@PasswordHash varchar(256)
)
AS
BEGIN
    UPDATE [dbo].[Users]
    SET
        [PublicId]=@PublicId,
        [UserName]=@UserName,
        [Email]=@Email,
        [Active]=@Active,
        [PasswordHash]=@PasswordHash
WHERE        [Id]=@Id
END

GO


