----------------------------------------
-- Generated by Iris Generator
-- The 7/8/2014 at 4:38 PM

-- The %D% at %T% :Roles
-- 5 stored procedures to generate.


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Roles_Select_All'))
drop procedure sp_Roles_Select_All


GO


Create Procedure sp_Roles_Select_All
AS
BEGIN
    SELECT [Id],[PublicId],[Name],[Active]
    FROM [dbo].[Roles]
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Roles_Select_One'))
drop procedure sp_Roles_Select_One


GO


Create Procedure sp_Roles_Select_One
(
@Id int
)
AS
BEGIN
    SELECT [Id],[PublicId],[Name],[Active]
    FROM [dbo].[Roles]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Roles_Insert'))
drop procedure sp_Roles_Insert


GO


Create Procedure sp_Roles_Insert
(
@PublicId uniqueidentifier,
@Name varchar(50),
@Active bit
)
AS
BEGIN
    INSERT INTO [dbo].[Roles]
    (
        [PublicId],
[Name],
[Active]
    )
    VALUES
    (
        @PublicId,
@Name,
@Active

    )
    Select @@identity;
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Roles_Delete'))
drop procedure sp_Roles_Delete


GO


Create Procedure sp_Roles_Delete
(
@Id int
)
AS
BEGIN
    DELETE FROM [dbo].[Roles]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Roles_Update'))
drop procedure sp_Roles_Update


GO


Create Procedure sp_Roles_Update
(
@Id int,
@PublicId uniqueidentifier,
@Name varchar(50),
@Active bit
)
AS
BEGIN
    UPDATE [dbo].[Roles]
    SET
        [PublicId]=@PublicId,
        [Name]=@Name,
        [Active]=@Active
WHERE        [Id]=@Id
END

GO


-- The %D% at %T% :UserRoles
-- 7 stored procedures to generate.


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Select_UserRoless_By_UserId'))
drop procedure sp_Select_UserRoless_By_UserId


GO


Create Procedure sp_Select_UserRoless_By_UserId
(
@UserId int
)
AS
BEGIN
    SELECT [Id],[RoleId],[UserId],[Active]
    FROM [dbo].[UserRoles]
    WHERE
        [UserId]=@UserId
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Select_UserRoless_By_RoleId'))
drop procedure sp_Select_UserRoless_By_RoleId


GO


Create Procedure sp_Select_UserRoless_By_RoleId
(
@RoleId int
)
AS
BEGIN
    SELECT [Id],[RoleId],[UserId],[Active]
    FROM [dbo].[UserRoles]
    WHERE
        [RoleId]=@RoleId
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_UserRoles_Select_All'))
drop procedure sp_UserRoles_Select_All


GO


Create Procedure sp_UserRoles_Select_All
AS
BEGIN
    SELECT [Id],[RoleId],[UserId],[Active]
    FROM [dbo].[UserRoles]
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_UserRoles_Select_One'))
drop procedure sp_UserRoles_Select_One


GO


Create Procedure sp_UserRoles_Select_One
(
@Id int
)
AS
BEGIN
    SELECT [Id],[RoleId],[UserId],[Active]
    FROM [dbo].[UserRoles]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_UserRoles_Insert'))
drop procedure sp_UserRoles_Insert


GO


Create Procedure sp_UserRoles_Insert
(
@RoleId int,
@UserId int,
@Active bit
)
AS
BEGIN
    INSERT INTO [dbo].[UserRoles]
    (
        [RoleId],
[UserId],
[Active]
    )
    VALUES
    (
        @RoleId,
@UserId,
@Active

    )
    Select @@identity;
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_UserRoles_Delete'))
drop procedure sp_UserRoles_Delete


GO


Create Procedure sp_UserRoles_Delete
(
@Id int
)
AS
BEGIN
    DELETE FROM [dbo].[UserRoles]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_UserRoles_Update'))
drop procedure sp_UserRoles_Update


GO


Create Procedure sp_UserRoles_Update
(
@Id int,
@RoleId int,
@UserId int,
@Active bit
)
AS
BEGIN
    UPDATE [dbo].[UserRoles]
    SET
        [RoleId]=@RoleId,
        [UserId]=@UserId,
        [Active]=@Active
WHERE        [Id]=@Id
END

GO


-- The %D% at %T% :Users
-- 5 stored procedures to generate.


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Users_Select_All'))
drop procedure sp_Users_Select_All


GO


Create Procedure sp_Users_Select_All
AS
BEGIN
    SELECT [Id],[PublicId],[UserName],[Email],[Active],[PasswordHash]
    FROM [dbo].[Users]
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Users_Select_One'))
drop procedure sp_Users_Select_One


GO


Create Procedure sp_Users_Select_One
(
@Id int
)
AS
BEGIN
    SELECT [Id],[PublicId],[UserName],[Email],[Active],[PasswordHash]
    FROM [dbo].[Users]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Users_Insert'))
drop procedure sp_Users_Insert


GO


Create Procedure sp_Users_Insert
(
@PublicId uniqueidentifier,
@UserName varchar(50),
@Email varchar(150),
@Active bit,
@PasswordHash varchar(100)
)
AS
BEGIN
    INSERT INTO [dbo].[Users]
    (
        [PublicId],
[UserName],
[Email],
[Active],
[PasswordHash]
    )
    VALUES
    (
        @PublicId,
@UserName,
@Email,
@Active,
@PasswordHash

    )
    Select @@identity;
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Users_Delete'))
drop procedure sp_Users_Delete


GO


Create Procedure sp_Users_Delete
(
@Id int
)
AS
BEGIN
    DELETE FROM [dbo].[Users]
    WHERE
        [Id]=@Id
END

GO


if exists (select * from sys.objects where ([type] = 'P' and [name]='sp_Users_Update'))
drop procedure sp_Users_Update


GO


Create Procedure sp_Users_Update
(
@Id int,
@PublicId uniqueidentifier,
@UserName varchar(50),
@Email varchar(150),
@Active bit,
@PasswordHash varchar(100)
)
AS
BEGIN
    UPDATE [dbo].[Users]
    SET
        [PublicId]=@PublicId,
        [UserName]=@UserName,
        [Email]=@Email,
        [Active]=@Active,
        [PasswordHash]=@PasswordHash
WHERE        [Id]=@Id
END

GO


